### ISSUE TITLE
Spaces in domain are valid

### ISSUE THREAD

**Issue by AlexWayfer** [afair/email_address#13]
```ruby
EmailAddress.valid? 'user@qq.co m' # => true
```
Is it defined (expected) behavior? Why does it work this way? Yes, `qq.co` exists, but…

**Comment by AlexWayfer** [comment]
Another example:

```ruby
> EmailAddress.valid? 'user@            comversion.co m' # => true
```

`comversion.com` exists, but `comversion.co` doesn't. And spaces after `@`, yeah.

**Comment by afair** [comment]
Thanks for the report. Spaces in the domain are invalid, but the library "cleans" the address by downcasing and removing spaces from the domain. These "helpers" have been a problem before and should be opted into.

I should not "fix" the address by removing spaces unless `host_remove_spaces:true` is set.

```ruby
EmailAddress.new("asdf@YA hoo.com").to_s #=> "asdf@yahoo.com"
EmailAddress.valid?("asdf@YA hoo.com") #=> false
EmailAddress.valid?("asdf@YA hoo.com", host_remove_spaces:true) #=> true
```

**Comment by AlexWayfer** [comment]
Great, thank you!

**Comment by AlexWayfer** [comment]
But why the library removes spaces? Maybe you want to use [`String#strip`](http://ruby-doc.org/core-2.4.2/String.html#method-i-strip) instead of `#gsub`?

**Comment by afair** [comment]
I have noticed people leave spaces in the email address unintentionally. I have been in the habit of removing them while sanitizing input. Since .valid?() is the major use case, it shouldn't validate on any such transformations

String#strip removes spaces only at the beginning and end, while #gsub will also remove them from the middle of the string.

**Comment by AlexWayfer** [comment]
Okay, thank you.

**Comment by afair** [comment]
I just released gem version 0.1.5 with this fix and some others from yesterday!

**Comment by AlexWayfer** [comment]
Excuse me:

```ruby
EmailAddress.valid? 'asdf@YA hoo.com', dns_lookup: :off # => true
EmailAddress.valid? 'asdf@YA hoo.com', dns_lookup: :off, host_remove_spaces: true # => true
EmailAddress.valid? 'asdf@YA hoo.com', dns_lookup: :off, host_remove_spaces: false # => true
```

:disappointed: 

I think it should returns `false` for any case unless `host_remove_spaces` is `true`.

**Comment by afair** [comment]
I pushed a fix for this. It wasn't validating the format of the domain name without a DNS lookup. I refactored the validations to capture more errors and give more detailed error messages (though I'm not sure if that's a good thing). Do you want to verify before I release yet again? :-) PR's accepted!

**Comment by AlexWayfer** [comment]
> Do you want to verify before I release yet again? :-)

Yes, I'll try it tomorrow! Thank you.

**Comment by AlexWayfer** [comment]
> Yes, I'll try it tomorrow! Thank you.

Everything is fine, I guess.

> PR's accepted!

PR with tests for `domain_invalid` error made.

**Comment by AlexWayfer** [comment]
Oh, wait, please.

**Comment by AlexWayfer** [comment]
```ruby
EmailAddress::Local.new('use r').valid? # => true
EmailAddress.valid?('use r@google.com') # => true
```

But [here](http://verifalia.com/validate-email) it is syntax error for `use r@google.com`: "An invalid character has been detected in the provided sequence."

**Comment by afair** [comment]
Thanks again, @AlexWayfer 

Like `:host_remove_spaces`, there is a config for `local_fix:true`which removes spaces from the local part. That default has been true since inception, but I've come around to think it should be off by default, like for the host part.

```ruby
EmailAddress.error('use r@gmail.com', local_fix:false) #=> "Invalid Recipient/Mailbox"
2.4.1 :008 > EmailAddress.error('user@gmail.com', local_fix:false) #=> "Invalid Recipient/Mailbox"
2.4.1 :009 > EmailAddress.error('user12@gmail.com', local_fix:false) #=> nil
```
Note that gmail local part must be in 5..64 characters long in the second example

I'll change that default to `local_fix: false` and release!

**Comment by AlexWayfer** [comment]
Thank you!

**Comment by AlexWayfer** [comment]
But what about default behavior for email addresses with spaces around email address parts?

```ruby
pry: main > EmailAddress.valid? 'user@google.com'
=> true
pry: main > EmailAddress.valid? 'user @google.com'
=> false
pry: main > EmailAddress.valid? ' user@google.com'
=> true
pry: main > EmailAddress.valid? ' user@ google.com'
=> true
pry: main > EmailAddress.valid? ' user@ google .com'
=> false
pry: main > EmailAddress.valid? ' user@ google.com '
=> true
```

**Comment by afair** [comment]
I consider those as valid, just needing clean-up from forms, as everyone should be doing. Only the "inside" value is significant, like submitting a "  1   " in a numeric field. Can you imagine telling a user that their email address is wrong because there is a trailing space they can't see or understand is a problem?

You can use the .normal() method to normalize or edit the value. 

```ruby
EmailAddress.normal("   user@Yahoo.com  ") #=> "user@yahoo.com"
e = EmailAddress.new("  user@Yahoo.com   ") #=> => #<EmailAddress::Address:....>
e.normal #=> "user@yahoo.com"
e.valid? #=> true
```

**Comment by afair** [comment]
Oh, I just saw "user@ google.com" ... that's inconsistent
