### ISSUE TITLE
Can judge whether target email is temporary?

### ISSUE THREAD

**Issue by OuGe95** [afair/email_address#39]
Hi, I am now facing with a troublesome problem. Some people maliciously use temporary email accounts to register, logged into the site, and made bad behavior. So I want to disable the registration function of temporary email. But I how to judge target email is temporary? Can you help me? Thank!
ps: [Ten Minutes Mail](http://mail.bccto.me/) is one of the most famous.

**Comment by afair** [comment]
This is a hard problem that I know firsthand, because there are so many operators running many domains used to register these addresses. I think using a RBL (like http://www.anti-abuse.org/multi-rbl-check/) may move the problems up to the operator level, but ultimately, we can't maintain such a list in this gem. An active RBL DNS server would be required.  Also, anyone can create a fake email account on their own domains or with their own address with a "me+malicious@gmail.com" address tag (we can drop the +malicious, but some email servers can do even harder to match separators.)

Email (for senders) has moved to a reputation and engagement tracking system. Until such a system is deployed universally for receivers, we can't solve this problem without resorting to a credit card proxy as reputations.

**Comment by OuGe95** [comment]
Ok, I understand, though very frustrated, thank you for your response and Suggestions
