### ISSUE TITLE
Trailing underscore in mailbox returns empty error

### ISSUE THREAD

**Issue by yanismydj** [afair/email_address#41]
I had a user reporting that they could not reset their password in Devise.  Their email has a mailbox with a trailing underscore (`exampleemail_@gmail.com`), but the `email_address` gem is returning `.valid?` as `false`, and `.error` as empty string.  This is different from https://github.com/afair/email_address/issues/35 as the issue is not that we are incorrectly marking the email as invalid, but rather that we are simply returning a nil/empty error message which makes it difficult to give feedback to the user.

**Comment by afair** [comment]
Try unreleased master branch for your temp fix...

 TRY #14 Fix... untested for now

Hi, I'm away and can't run the test on my current environment.
I made the change that should allow trailing underscore.

 Good luck!

It's just a REGEX change, so you can look at this commit and try alternatives.

**Comment by afair** [comment]
I apologize, but what I did on my travels never seemed to make it to the server. I'm home now, jet lagged, and just tested and  pushed a fix for this. You can try to use this from your Gemfile pointing to the head of the master branch instead of the gem name. I'll try to release this once I do more tests.

**Comment by olleolleolle** [comment]
@yanismydj Does this fix your original issue?
