### ISSUE TITLE
v0.1.14 breaks compatibility with Ruby versions before 2.4.0

### ISSUE THREAD

**Issue by smnkrt** [afair/email_address#58]
`Regexp#match?` was introduced in Ruby 2.4.0 and code using older versions of Ruby can expect errors related to `match?` not being defined.

it's used for example [here](https://github.com/afair/email_address/commit/f2bd5a797ef05414f4a20dc64858df4ceca12af3#diff-61da8d1ef747c5bd7efdb2574a5b4c9aR218)

Either docs could be updated or code can check which `RUBY_VERSION ` and based on version using `match?`, WDYT?

**Comment by afair** [comment]
Fixed and released. While I'm not targeting End-of-Life rubies, I'm happy to keep syntax compatible. I run this through travis including ruby 2.3.7 which did work. 

The problem was actually rubocop. It "fixed" the syntax on that line to the "new, preferred" way, not the way that works most universally. Great for an app, not cool for a library supporting multiple ruby versions.
