### ISSUE TITLE
EmailAddress.matches?(address, 'google') #=> 'google' (true) Error in Version 0.1.20

### ISSUE THREAD

**Issue by fidenz-academy** [afair/email_address#79]
In one of my projects, we use this method to detect that users had google related emails or not. but it seems to be not working on the new version.

If I use email like test@gmail.com it will say its a google email but when I use test@<Some other domain which uses google servie>.com will not return google and it returns false

This works in the older version 0.1.12 (Which I was using) but not in the newer version can someone let me know what is happening there?

Thanks

**Comment by afair** [comment]
Hello! Thank you for your question. Could you check your question again for me please? 

`test@.com` is missing the domain name (like gmail) so is not a valid domain name or email address. Is this your intended email address? If so the difference was likely a bug fixed since version 0.1.12.

Let me know if I have missed something :-)
