### ISSUE TITLE
net-smtp gem required with Ruby >= 3.1

### ISSUE THREAD

**Issue by cseelus** [afair/email_address#87]
Since upgrading to Ruby 3.1, I had to manually add [`gem 'net-smtp'`](https://github.com/ruby/net-smtp) to the Gemfiles of our projects which use the `email_address` gem.

In any case: Thanks for this valuable little library :-)

**Comment by afair** [comment]
Thanks for bringing this up. I have released v0.2.2 to address ruby 3.1 support

Specifically, net/smtp was only used for an experimental feature that no one should actually use: connecting to the mail server to validate.

Instead of adding this dependency, I removed the require. Anyone needed to do the SMTP validation (and really they shouldn't) must now add the "net-smtp" gem and require it manually.
